jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:

  - task: UseRubyVersion@0
    inputs:
      versionSpec: '= 2.4'

  - script: |
      gem update --system
      gem install bundler
      gem uninstall did_you_mean
    displayName: 'before install'

  - script: |
      bundle exec thor spec
    displayName: 'bundle exec thor spec'
